### ISSUE TITLE
pledge.cc:42: error: no matching function for call to 'SetMethod

### ISSUE THREAD

**Issue by mikeputnam** [qbit/node-pledge#2]
`$ uname -a
OpenBSD mikelappy.slayer 5.8 GENERIC#1066 i386`

```
[mike@mikelappy src]$ npm install --save node-pledge

> node-pledge@1.0.2 install /home/mike/src/node_modules/node-pledge
> node-gyp rebuild

gmake: Entering directory '/home/mike/src/node_modules/node-pledge/build'
  g++ '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/mike/.node-gyp/0.10.35/src -I/home/mike/.node-gyp/0.10.35/deps/uv/include -I/home/mike/.node-gyp/0.10.35/deps/v8/include  -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -m32 -O2 -fno-strict-aliasing -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF ./Release/.deps/Release/obj.target/pledge/pledge.o.d.raw  -c -o Release/obj.target/pledge/pledge.o ../pledge.cc
../pledge.cc:11: error: 'v8::FunctionCallbackInfo' has not been declared
../pledge.cc:18: error: expected ',' or '...' before '<' token
../pledge.cc:18: error: ISO C++ forbids declaration of 'FunctionCallbackInfo' with no type
../pledge.cc: In function 'void openbsdPledge::Pledge(int)':
../pledge.cc:19: error: 'args' was not declared in this scope
../pledge.cc:22: error: 'class v8::Isolate' has no member named 'ThrowException'
../pledge.cc:23: error: 'NewFromUtf8' is not a member of 'v8::String'
../pledge.cc:28: error: 'class v8::Isolate' has no member named 'ThrowException'
../pledge.cc:29: error: 'NewFromUtf8' is not a member of 'v8::String'
../pledge.cc:34: error: 'pledge' was not declared in this scope
../pledge.cc: In function 'void openbsdPledge::Init(v8::Local<v8::Object>)':
../pledge.cc:42: error: no matching function for call to 'SetMethod(v8::Local<v8::Object>&, const char [5], void (&)(int))'
pledge.target.mk:83: recipe for target 'Release/obj.target/pledge/pledge.o' failed
gmake: *** [Release/obj.target/pledge/pledge.o] Error 1
gmake: Leaving directory '/home/mike/src/node_modules/node-pledge/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System OpenBSD 5.8
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mike/src/node_modules/node-pledge
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! node-pledge@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pledge@1.0.2 install script.
npm ERR! This is most likely a problem with the node-pledge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-pledge
npm ERR! There is likely additional logging output above.
npm ERR! System OpenBSD 5.8
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "node-pledge"
npm ERR! cwd /home/mike/src
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

```

**Comment by qbit** [comment]
Unfortunately this currently has some stuff that is from a newer version of node. None of it is super required.. I will do some backporting to get it to work.

Also there is a diff on ports@ for node-v4.2.1 - it builds (and tests well for me) on 5.7, so I am guessing it would work well on 5.8 as well. (I will find out for sure)

**Comment by qbit** [comment]
@mikeputnam it should work now! I have tested with 0.10.35 and 4.2.1. Can you verify?

**Comment by mikeputnam** [comment]
Retried on -stable got the below error.

Retried on latest snapshot, installs fine!



```
[mike@mikelappy temp]$ uname -a
OpenBSD mikelappy.slayer 5.8 GENERIC#1066 i386
[mike@mikelappy temp]$ npm install --save node-pledge
\
> node-pledge@1.0.3 install /home/mike/src/temp/node_modules/node-pledge
> node-gyp rebuild

gmake: Entering directory '/home/mike/src/temp/node_modules/node-pledge/build'
  g++ '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/mike/.node-gyp/0.10.35/src -I/home/mike/.node-gyp/0.10.35/deps/uv/include -I/home/mike/.node-gyp/0.10.35/deps/v8/include  -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -m32 -O2 -fno-strict-aliasing -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF ./Release/.deps/Release/obj.target/pledge/pledge_10x.o.d.raw  -c -o Release/obj.target/pledge/pledge_10x.o ../pledge_10x.cc
../pledge_10x.cc: In function 'v8::Handle<v8::Value> Pledge(const v8::Arguments&)':
../pledge_10x.cc:23: error: 'pledge' was not declared in this scope
pledge.target.mk:83: recipe for target 'Release/obj.target/pledge/pledge_10x.o' failed
gmake: *** [Release/obj.target/pledge/pledge_10x.o] Error 1
gmake: Leaving directory '/home/mike/src/temp/node_modules/node-pledge/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System OpenBSD 5.8
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mike/src/temp/node_modules/node-pledge
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! node-pledge@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pledge@1.0.3 install script.
npm ERR! This is most likely a problem with the node-pledge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-pledge
npm ERR! There is likely additional logging output above.
npm ERR! System OpenBSD 5.8
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "node-pledge"
npm ERR! cwd /home/mike/src/temp
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

```

**Comment by qbit** [comment]
Ah, yeah - pledge(2) isn't in stable :P 

Thanks for testing! I will close!
